### ISSUE TITLE
Theme works only when put under 'gui:'

### ISSUE THREAD

**Issue by cmon1701** [dracula/lazyigt#2]
To Do: change [dracula.yml](https://github.com/dracula/lazygit/blob/main/config/dracula.yml)
so that it looks like below.
(OR: State in the documentation to put the code under "gui:")

```
gui:
  # DRACULA
  theme:
    activeBorderColor:
      - "#FF79C6"
      - bold
 <…>
```
